VALID_WOW_SERVERS = [
    ["Aegwynn", 'PvP'],
    ["Aerie Peak", 'PvE'], 
    ["Agamagga", 'PvP'], 
    ["Aggramar", 'PvE'], 
    ["Akama", 'PvP'], 
    ["Alexstrasza", 'PvE'], 
    ["Alleria", 'PvE'], 
    ["Altar of Storms", 'PvP'],
    ["Alterac Mountains", 'PvP'],
    ["Aman'Thul", 'PvE'],
    ["Andorhal", 'PvP'],
    ["Anetheron", 'PvP'],
    ["Antonidas", 'PvE'],
    ["Anub'arak", 'PvP'],
    ["Anvilmar", 'PvE'],
    ["Arathor", 'PvE'],
    ["Archimonde", 'PvP'],
    ["Area 52", 'PvE'],
    ["Argent Dawn", 'RP'],
    ["Arthas", 'PvP'],
    ["Arygos", 'PvE'],
    ["Auchindoun", 'PvP'],
    ["Azgalor", 'PvP'],
    ["Azjol-Nerub", 'PvE'],
    ["Azshara", 'PvP'],
    ["Azuremyst", 'PvE'],
    ["Baelgun", 'PvE'],
    ["Balnazzar", 'PvP'],
    ["Barthilas", 'PvP'],
    ["Black Dragonflight", 'PvP'],
    ["Blackhand", 'PvE'],
    ["Blackrock", 'PvP'],
    ["Blackwater Raiders", 'RP'],
    ["Blackwing Lair", 'PvP'],
    ["Blade's Edge", 'PvE'],
    ["Bladefist", 'PvE'],
    ["Bleeding Hollow", 'PvP'],
    ["Blood Furnace", 'PvP'],
    ["Bloodhoof", 'PvE'],
    ["Bloodscalp", 'PvP'],
    ["Bonechewer", 'PvP'],
    ["Borean Tundra", 'PvE'],
    ["Boulderfist", 'PvP'],
    ["Bronzebeard", 'PvE'],
    ["Burning Blade", 'PvP'],
    ["Burning Legion", 'PvP'],
    ["Caelestrasz", 'PvE'],
    ["Cairne", 'PvE'],
    ["Cenarion Circle", 'RP'],
    ["Cenarius", 'PvE'],
    ["Cho'gall", 'PvP'],
    ["Chromaggus", 'PvP'],
    ["Coilfang", 'PvP'],
    ["Crushridge", 'PvP'],
    ["Daggerspine", 'PvP'],
    ["Dalaran", 'PvE'],
    ["Dalvengyr", 'PvP'],
    ["Dark Iron", 'PvP'],
    ["Darkspear", 'PvP'],
    ["Darrowmere", 'PvE'],
    ["Dath'Remar", 'PvE'],
    ["Dawnbringer", 'PvE'],
    ["Deathwing", 'PvP'],
    ["Demon Soul", 'PvP'],
    ["Dentarg", 'PvE'],
    ["Destromath", 'PvP'],
    ["Dethecus", 'PvP'],
    ["Detheroc", 'PvP'],
    ["Doomhammer", 'PvE'],
    ["Draenor", 'PvE'],
    ["Dragonblight", 'PvE'],
    ["Dragonmaw", 'PvP'],
    ["Drak'Tharon", 'PvP'],
    ["Drak'thul", 'PvE'],
    ["Draka", 'PvE'],
    ["Drakkari", 'PvP'],
    ["Dreadmaul", 'PvP'],
    ["Drenden", 'PvE'],
    ["Dunemaul", 'PvP'],
    ["Durotan", 'PvE'],
    ["Duskwood", 'PvE'],
    ["Earthen Ring", 'RP'],
    ["Echo Isles", 'PvE'],
    ["Eitrigg", 'PvE'],
    ["Eldre'Thalas", 'PvE'],
    ["Elune", 'PvE'],
    ["Emerald Dream", 'RP PvP'],
    ["Eonar", 'PvE'],
    ["Eredar", 'PvP'],
    ["Executus", 'PvP'],
    ["Exodar", 'PvE'],
    ["Farstriders", 'RP'],
    ["Feathermoon", 'RP'],
    ["Fenris", 'PvE'],
    ["Firetree", 'PvP'],
    ["Fizzcrank", 'PvE'],
    ["Frostmane", 'PvP'],
    ["Frostmourne", 'PvP'],
    ["Frostwolf", 'PvP'],
    ["Galakrond", 'PvE'],
    ["Garithos", 'PvP'],
    ["Garona", 'PvE'],
    ["Garrosh", 'PvE'],
    ["Ghostlands", 'PvE'],
    ["Gilneas", 'PvE'],
    ["Gnomeregan", 'PvE'],
    ["Gorefiend", 'PvP'],
    ["Gorgonnash", 'PvP'],
    ["Greymane", 'PvE'],
    ["Grizzly Hills", 'PvE'],
    ["Gul'dan", 'PvP'],
    ["Gundrak", 'PvP'],
    ["Gurubashi", 'PvP'],
    ["Hakkar", 'PvP'],
    ["Haomarush", 'PvP'],
    ["Hellscream", 'PvE'],
    ["Hydraxis", 'PvE'],
    ["Hyjal", 'PvE'],
    ["Icecrown", 'PvE'],
    ["Illidan", 'PvP'],
    ["Jaedenar", 'PvP'],
    ["Jubei'Thos", 'PvP'],
    ["Kael'thas", 'PvE'],
    ["Kalecgos", 'PvP'],
    ["Kargath", 'PvE'],
    ["Kel'Thuzad", 'PvP'],
    ["Khadgar", 'PvE'],
    ["Khaz Modan", 'PvE'],
    ["Khaz'goroth", 'PvE'],
    ["Kil'jaeden", 'PvP'],
    ["Kilrogg", 'PvE'],
    ["Kirin Tor", 'RP'],
    ["Korgath", 'PvP'],
    ["Korialstrasz", 'PvE'],
    ["Kul Tiras", 'PvE'],
    ["Laughing Skull", 'PvP'],
    ["Lethon", 'PvP'],
    ["Lightbringer", 'PvE'],
    ["Lightning's Blade", 'PvP'],
    ["Lightninghoof", 'RP PvP'],
    ["Llane", 'PvE'],
    ["Lothar", 'PvE'],
    ["Madoran", 'PvE'],
    ["Maelstrom", 'RP PvP'],
    ["Magtheridon", 'PvP'],
    ["Maiev", 'PvP'],
    ["Mal'Ganis", 'PvP'],
    ["Malfurion", 'PvE'],
    ["Malorne", 'PvP'],
    ["Malygos", 'PvE'],
    ["Mannoroth", 'PvP'],
    ["Medivh", 'PvE'],
    ["Misha", 'PvE'],
    ["Mok'Nathal", 'PvE'],
    ["Moon Guard", 'RP'],
    ["Moonrunner", 'PvE'],
    ["Mug'thol", 'PvP'],
    ["Muradin", 'PvE'],
    ["Nagrand", 'PvE'],
    ["Nathrezim", 'PvP'],
    ["Nazgrel", 'PvE'],
    ["Nazjatar", 'PvP'],
    ["Ner'zhul", 'PvP'],
    ["Nesingwary", 'PvE'],
    ["Nordrassil", 'PvE'],
    ["Norgannon", 'PvE'],
    ["Onyxia", 'PvP'],
    ["Perenolde", 'PvE'],
    ["Proudmoore", 'PvE'],
    ["Quel'dorei", 'PvE'],
    ["Quel'Thalas", 'PvE'],
    ["Ragnaros", 'PvP'],
    ["Ravencrest", 'PvE'],
    ["Ravenholdt", 'RP PvP'],
    ["Rexxar", 'PvE'],
    ["Rivendare", 'PvP'],
    ["Runetotem", 'PvE'],
    ["Sargeras", 'PvP'],
    ["Saurfang", 'PvE'],
    ["Scarlet Crusade", 'RP'],
    ["Scilla", 'PvP'],
    ["Sen'jin", 'PvE'],
    ["Sentinels", 'RP'],
    ["Shadow Council", 'RP'],
    ["Shadowmoon", 'PvP'],
    ["Shadowsong", 'PvE'],
    ["Shandris", 'PvE'],
    ["Shattered Halls", 'PvP'],
    ["Shattered Hand", 'PvP'],
    ["Shu'halo", 'PvE'],
    ["Silver Hand", 'RP'],
    ["Silvermoon", 'PvE'],
    ["Sisters of Elune", 'RP'],
    ["Skullcrusher", 'PvP'],
    ["Skywall", 'PvE'],
    ["Smolderthorn", 'PvP'],
    ["Spinebreaker", 'PvP'],
    ["Spirestone", 'PvP'],
    ["Staghelm", 'PvE'],
    ["Steamwheedle Cartel", 'RP'],
    ["Stonemaul", 'PvP'],
    ["Stormrage", 'PvE'],
    ["Stormreaver", 'PvP'],
    ["Stormscale", 'PvP'],
    ["Suramar", 'PvE'],
    ["Tanaris", 'PvE'],
    ["Terenas", 'PvE'],
    ["Terokkar", 'PvE'],
    ["Thaurissan", 'PvP'],
    ["The Forgotten Coast", 'PvP'],
    ["The Scryers", 'RP'],
    ["The Underbog", 'PvP'],
    ["The Venture Co", 'RP PvP'],
    ["Thorium Brotherhood", 'RP'],
    ["Thrall", 'PvE'],
    ["Thunderhorn", 'PvE'],
    ["Thunderlord", 'PvP'],
    ["Tichondrius", 'PvP'],
    ["Tortheldrin", 'PvP'],
    ["Trollbane", 'PvE'],
    ["Turalyon", 'PvE'],
    ["Twisting Nether", 'RP PvP'],
    ["Uldaman", 'PvE'],
    ["Uldum", 'PvE'],
    ["Undermine", 'PvE'],
    ["Ursin", 'PvP'],
    ["Uther", 'PvE'],
    ["Vashj", 'PvP'],
    ["Vek'nilash", 'PvE'],
    ["Velen", 'PvE'],
    ["Warsong", 'PvP'],
    ["Whisperwind", 'PvE'],
    ["Wildhammer", 'PvP'],
    ["Windrunner", 'PvE'],
    ["Winterhoof", 'PvE'],
    ["Wyrmrest Accord", 'RP'],
    ["Ysera", 'PvE'],
    ["Ysondre", 'PvP'],
    ["Zangarmarsh", 'PvE'],
    ["Zul'jin", 'PvE'],
    ["Zuluhed", 'PvP']
  ]
  
  puts "Creating WoW Games..."
  VALID_WOW_SERVERS.each do |server_name, server_type|
    Wow.create(:faction => "Alliance", :server_name => server_name, :server_type => server_type)
    Wow.create(:faction => "Horde", :server_name => server_name, :server_type => server_type)
  end
