VALID_SWTOR_SERVERS = [
  ["Ajunta Pall", "RP-PvP", "West"],
  ["Anchorhead", "PvP", "East"],
  ["Anturi Reach", "PvE", "East"],
  ["Assassins of Sion", "PvE", "East"],
  ["Axial Park", "PvE", "East"],
  ["Begeren Colony", "RP-PvE", "West"],
  ["Belgoth's Beacon", "PvP", "East"],
  ["Black Vulkars", "PvP", "West"],
  ["Bondar Crystal", "PvP", "East"],
  ["Canderous Ordo", "PvE", "East"],
  ["Cho Mai", "PvP", "East"],
  ["Colonel Tobin", "PvE", "East"],
  ["Corellian Run", "PvE", "East"],
  ["Crevasse City", "PvE", "East"],
  ["Daragon Trail", "PvP", "West"],
  ["Dark Reaper", "PvP", "West"],
  ["Darth Bandon", "PvE", "East"],
  ["Darth Malak", "PvP", "East"],
  ["Darth Sion", "PvE", "West"],
  ["Darth Xedrix", "PvE", "West"],
  ["Davik's Estate", "PvP", "East"],
  ["Death Wind Corridor", "PvP", "East"],
  ["Dreshdae Cantina", "PvE", "East"],
  ["Drooga's Pleasure Barge", "PvE", "West"],
  ["Eidolon Security", "PvE", "East"],
  ["Elysium", "PvE", "East"],
  ["Empress Teta", "PvE", "West"],
  ["Fa'athra", "PvE", "West"],
  ["Firaxan Shark", "PvE", "East"],
  ["Firkrann Crystal", "PvP", "East"],
  ["Fort Garnik", "PvE", "East"],
  ["Gardens of Talla ", "PvP", "East"],
  ["Gauntlet of Kressh", "PvE", "West"],
  ["Giradda the Hutt", "PvE", "East"],
  ["Grand Master Zym", "PvE", "East"],
  ["Hanharr", "PvE", "East"],
  ["Hedarr Soongh", "PvP", "East"],
  ["Helm of Graush", "PvP", "East"],
  ["Hyperspace Cannon", "PvE", "West"],
  ["ICE Breaker", "PvE", "East"],
  ["Infinite Empire", "PvP", "West"],
  ["Infinity Gate", "PvP", "East"],
  ["Iron Citadel", "PvP", "East"],
  ["Jedi Covenant", "PvE", "East"],
  ["Jung Ma", "RP-PvP", "East"],
  ["Juyo", "PvE", "East"],
  ["Kaas City", "PvE", "East"],
  ["Kaiburr Crystal", "PvE", "West"],
  ["Kath Hound", "RP-PvE", "East"],
  ["Kathol Rift", "PvE", "East"],
  ["Keetael", "PvE", "East"],
  ["Keller's Void", "PvE", "East"],
  ["Khoonda Militia", "PvE", "East"],
  ["Ki-Ta Kren", "PvE", "East"],
  ["Kinrath Spider", "PvP", "East"],
  ["Krath", "PvE", "West"],
  ["Krayiss Obelisk", "PvE", "East"],
  ["Krayt Dragon", "PvE", "East"],
  ["Lord Adraas", "RP-PvE", "East"],
  ["Lord Ieldis", "RP-PvE", "West"],
  ["Lord Praven", "PvE", "West"],
  ["Mandalore the Indomitable", "PvP", "West"],
  ["Mask of Nihilus", "PvE", "West"],
  ["Master Dorak", "PvE", "East"],
  ["Master Gnost-Dural", "PvE", "West"],
  ["Master Zhar Lestin", "PvE", "West"],
  ["Mind Trick", "PvE", "East"],
  ["Nadd's Sarcophagus", "PvP", "West"],
  ["Naddist Rebels", "PvP", "East"],
  ["Namadii Corridor", "PvE", "West"],
  ["Nathema", "PvE", "East"],
  ["Perlemian Trade Route", "PvE", "West"],
  ["Port Nowhere", "PvP", "East"],
  ["Prophecy of the Five", "PvP", "East"],
  ["Rakata Mind Prison", "PvP", "West"],
  ["Rubat Crystal", "RP-PvE", "East"],
  ["Rwookrrorro ", "PvP", "East"],
  ["Saber of Exar Kun", "PvP", "East"],
  ["Sanctum of the Exalted", "RP-PvE", "East"],
  ["Sedyn Kyne", "PvE", "East"],
  ["Shadow Hand", "PvE", "East"],
  ["Shadowtown", "PvP", "West"],
  ["Shien", "RP-PvE", "East"],
  ["Shii-Cho", "PvE", "East"],
  ["Sith Meditation Sphere", "PvE", "East"],
  ["Sith Wyrm", "PvE", "East"],
  ["Soresu", "PvE", "West"],
  ["Space Slug", "PvE", "West"],
  ["Sword of Ajunta Pall", "PvP", "East"],
  ["Tarro Blood", "PvE", "East"],
  ["Telos Restoration Project", "PvE", "East"],
  ["Terentatek", "PvP", "East"],
  ["Thana Vesh", "PvE", "East"],
  ["The Bastion", "PvP", "West"],
  ["The Constant", "PvE", "East"],
  ["The Corsair", "PvE", "East"],
  ["The Courageous", "PvE", "East"],
  ["The Crucible Pits", "PvP", "West"],
  ["The Deadweight ", "PvP", "East"],
  ["The Defenestrator", "PvE", "East"],
  ["The Ebon Hawk", "RP-PvE", "East"],
  ["The Fatman", "PvP", "East"],
  ["The Harbinger", "PvE", "West"],
  ["The Jekk'Jekk Tarr", "PvE", "West"],
  ["The Maw", "PvP", "West"],
  ["The Razor", "PvE", "East"],
  ["The Shadowlands", "PvE", "East"],
  ["The Swiftsure", "PvP", "West"],
  ["The Twin Spears", "PvP", "East"],
  ["Thendys Noori ", "PvP", "East"],
  ["Veeboo Lunx", "PvE", "West"],
  ["Veela", "PvP", "East"],
  ["Ven Zallow", "RP-PvP", "East"],
  ["Vornskr", "PvE", "West"],
  ["Vrook Lamar", "RP-PvE", "West"],
  ["Vulkar Highway", "PvP", "East"],
  ["Wall of Light", "PvE", "West"],
  ["Warriors of the Shadow", "PvP", "West"],
  ["Whitebeam Run", "PvE", "East"],
  ["Wound in the Force", "PvP", "West"],
  ["Zaalbar", "PvE", "West"],
  ["Zakkeg BEast", "PvE", "West"],
  ["Zez-Kai Ell", "PvE", "East"],
  ["Ahto City", "PvP", "English"],
  ["Atris", "PvP", "French"],
  ["Bacca's Blade", "PvE", "English"],
  ["Bao-Dur", "PvE", "English"],
  ["Baron Deathmark", "PvP", "French"],
  ["Basilisk Droid", "PvP", "English"],
  ["Battle Meditation", "RP-PvE", "French"],
  ["Bloodworthy", "PvP", "English"],
  ["Blotus the Hutt", "PvP", "German"],
  ["Brianna", "PvP", "German"],
  ["Cassus Fett", "RP-PvE", "German"],
  ["Chuundar", "PvP", "English"],
  ["Darth Andeddu", "PvE", "German"],
  ["Darth Nihilus", "PvP", "French"],
  ["Darth Revan's Mask", "PvP", "German"],
  ["Darth Traya", "PvP", "German"],
  ["Dol Grenn", "PvP", "French"],
  ["Dreypa's Oubliette", "PvE", "German"],
  ["Dune Bantha", "PvE", "English"],
  ["Dxun Battle Circle", "PvE", "English"],
  ["Exar Kun", "PvE", "German"],
  ["Exis Station", "PvP", "German"],
  ["Eye of Ashlanae", "PvE", "English"],
  ["Flames of the Crucible", "PvE", "English"],
  ["Force Harvester", "PvE", "German"],
  ["Frostclaw", "PvE", "English"],
  ["Gnawer's Roost", "PvP", "German"],
  ["Goluud Corridor", "PvE", "English"],
  ["Handmaidens of Atris", "PvE", "German"],
  ["Hex Droid", "PvP", "English"],
  ["Hidden Beks", "PvE", "English"],
  ["Hrakert Rift", "PvP", "French"],
  ["Hssiss", "PvE", "French"],
  ["Huntmaster", "RP-PvP", "French"],
  ["Hydian Way", "PvE", "English"],
  ["Jar'Kai Sword", "PvP", "German"],
  ["Jen'jidai", "RP-PvP", "German"],
  ["Kai-kan", "PvP", "English"],
  ["Kellian Jarro", "PvE", "English"],
  ["Kessel Run", "RP-PvE", "French"],
  ["Kissai Caste", "PvE", "French"],
  ["Legions of Lettow", "PvP", "English"],
  ["Lenico Gargantuan", "PvE", "German"],
  ["Loramarr", "PvP", "German"],
  ["Lord Calypho", "RP-PvP", "English"],
  ["Ludo Kressh", "PvE", "English"],
  ["Luka Sene", "PvE", "English"],
  ["Mantle of the Force", "PvE", "French"],
  ["Mecrosa Order", "PvP", "French"],
  ["Murakami Orchid", "PvE", "German"],
  ["Nightmare Lands", "PvE", "English"],
  ["Niman", "PvP", "English"],
  ["Odacer-Faustin Academy", "PvE", "German"],
  ["Opila Crystal", "PvE", "German"],
  ["Peragus Mining Facility", "PvE", "English"],
  ["Phateem Halls of Knowledge", "PvE", "French"],
  ["Pius Dea", "PvP", "German"],
  ["Princess Galia", "PvP", "French"],
  ["Rogue Moon", "PvE", "English"],
  ["Scepter of Ragnos", "PvP", "English"],
  ["Senator Contispex", "PvP", "English"],
  ["Shaltin Tunnels", "RP-PvE", "English"],
  ["Sith Triumvirate", "PvE", "German"],
  ["Sith'ari", "PvE", "English"],
  ["Sluis Shipyards", "PvE", "English"],
  ["Star Map", "PvP", "French"],
  ["Starstorm One", "PvP", "English"],
  ["Stereb Cities", "PvE", "German"],
  ["Supreme Commander Stantorrs", "PvE", "German"],
  ["T3-M4", "PvE", "German"],
  ["Tassaa Bareesh", "PvP", "English"],
  ["The Arkanian Legacy", "PvE", "English"],
  ["The Cinzia", "PvE", "German"],
  ["The Exile's Crystal", "PvP", "English"],
  ["The Jedi Tower", "PvE", "German"],
  ["The Krath Enchanter", "PvP", "German"],
  ["The Kumumgah", "PvP", "English"],
  ["The Progenitor", "RP-PvE", "English"],
  ["The Ravager", "PvP", "English"],
  ["The Red Eclipse", "PvE", "English"],
  ["The Restoration Zone", "PvP", "German"],
  ["The Shadow Runner", "PvP", "English"],
  ["Tomb of Freedon Nadd", "PvP", "English"],
  ["Tott Doneeta", "PvP", "English"],
  ["Trask Ulgo", "RP-PvE", "English"],
  ["Trayus Academy", "PvP", "English"],
  ["Ula Vii", "PvP", "English"],
  ["Uthar Wynn", "PvP", "English"],
  ["Vanjervalis Chain", "RP-PvE", "German"],
  ["Vodo-Siosk Baas", "PvE", "French"],
  ["Zayne Carrick", "RP-PvE", "German"],
  ["Dalborra", "PvE", "English"],
  ["Gav Daragon", "RP-PvE", "English"],
  ["Master Dar'Nala", "PvP", "English"]
]

puts "Creating SWTOR Games..."
VALID_SWTOR_SERVERS.each do |server_name, server_type|
  Swtor.create!(:faction => "Republic", :server_name => server_name, :server_type => server_type)
  Swtor.create!(:faction => "Empire", :server_name => server_name, :server_type => server_type)
end