VALID_SWTOR_SERVERS = [
  ["Ajunta PallLight", 'RP-PvP', '', 'West'],
  ["AnchorheadLight", 'PvP', 'East'],
  ["Anturi ReachLight", 'PvE', 'East'],
  ["Assassins of SionLight", 'PvE', 'East'],
  ["Axial ParkLight", 'PvE', 'East'],
  ["Begeren ColonyStandard", 'RP-PvE', '', 'West'],
  ["Belgoth's BeaconLight", 'PvP', 'East'],
  ["Black VulkarsLight", 'PvP', 'West'],
  ["Bondar CrystalLight", 'PvP', 'East'],
  ["Canderous OrdoStandard", 'PvE', 'East'],
  ["Cho MaiLight", 'PvP', 'East'],
  ["Colonel TobinLight", 'PvE', 'East'],
  ["Corellian RunStandard", 'PvE', 'East'],
  ["Crevasse CityLight", 'PvE', 'East'],
  ["Daragon TrailLight", 'PvP', 'West'],
  ["Dark ReaperLight", 'PvP', 'West'],
  ["Darth BandonLight", 'PvE', 'East'],
  ["Darth MalakLight", 'PvP', 'East'],
  ["Darth SionLight", 'PvE', 'West'],
  ["Darth XedrixLight", 'PvE', 'West'],
  ["Davik's EstateLight", 'PvP', 'East'],
  ["Death Wind CorridorLight", 'PvP', 'East'],
  ["Dreshdae CantinaLight", 'PvE', 'East'],
  ["Drooga's Pleasure BargeStandard", 'PvE', 'West'],
  ["Eidolon SecurityLight", 'PvE', 'East'],
  ["ElysiumLight", 'PvE', 'East'],
  ["Empress TetaLight", 'PvE', 'West'],
  ["Fa'athraLight", 'PvE', 'West'],
  ["Firaxan SharkLight", 'PvE', 'East'],
  ["Firkrann CrystalLight", 'PvP', 'East'],
  ["Fort GarnikLight", 'PvE', 'East'],
  ["Gardens of Talla Light", 'PvP', 'East'],
  ["Gauntlet of KresshLight", 'PvE', 'West'],
  ["Giradda the HuttLight", 'PvE', 'East'],
  ["Grand Master ZymLight", 'PvE', 'East'],
  ["HanharrLight", 'PvE', 'East'],
  ["Hedarr SoonghLight", 'PvP', 'East'],
  ["Helm of GraushLight", 'PvP', 'East'],
  ["Hyperspace CannonLight", 'PvE', 'West'],
  ["ICE BreakerLight", 'PvE', 'East'],
  ["Infinite EmpireLight", 'PvP', 'West'],
  ["Infinity GateLight", 'PvP', 'East'],
  ["Iron CitadelLight", 'PvP', 'East'],
  ["Jedi CovenantStandard", 'PvE', 'East'],
  ["Jung MaStandard", 'RP-PvP', '', 'East'],
  ["JuyoLight", 'PvE', 'East'],
  ["Kaas CityLight", 'PvE', 'East'],
  ["Kaiburr CrystalLight", 'PvE', 'West'],
  ["Kath HoundLight", 'RP-PvE', '', 'East'],
  ["Kathol RiftLight", 'PvE', 'East'],
  ["KeetaelLight", 'PvE', 'East'],
  ["Keller's VoidLight", 'PvE', 'East'],
  ["Khoonda MilitiaLight", 'PvE', 'East'],
  ["Ki-Ta KrenLight", 'PvE', 'East'],
  ["Kinrath SpiderLight", 'PvP', 'East'],
  ["KrathLight", 'PvE', 'West'],
  ["Krayiss ObeliskLight", 'PvE', 'East'],
  ["Krayt DragonLight", 'PvE', 'East'],
  ["Lord AdraasLight", 'RP-PvE', '', 'East'],
  ["Lord IeldisLight", 'RP-PvE', '', 'West'],
  ["Lord PravenLight", 'PvE', 'West'],
  ["Mandalore the IndomitableLight", 'PvP', 'West'],
  ["Mask of NihilusLight", 'PvE', 'West'],
  ["Master DorakLight", 'PvE', 'East'],
  ["Master Gnost-DuralLight", 'PvE', 'West'],
  ["Master Zhar LestinLight", 'PvE', 'West'],
  ["Mind TrickLight", 'PvE', 'East'],
  ["Nadd's SarcophagusLight", 'PvP', 'West'],
  ["Naddist RebelsLight", 'PvP', 'East'],
  ["Namadii CorridorLight", 'PvE', 'West'],
  ["NathemaLight", 'PvE', 'East'],
  ["Perlemian Trade RouteLight", 'PvE', 'West'],
  ["Port NowhereLight", 'PvP', 'East'],
  ["Prophecy of the FiveStandard", 'PvP', 'East'],
  ["Rakata Mind PrisonLight", 'PvP', 'West'],
  ["Rubat CrystalLight", 'RP-PvE', '', 'East'],
  ["Rwookrrorro Light", 'PvP', 'East'],
  ["Saber of Exar KunLight", 'PvP', 'East'],
  ["Sanctum of the ExaltedLight", 'RP-PvE', '', 'East'],
  ["Sedyn KyneLight", 'PvE', 'East'],
  ["Shadow HandLight", 'PvE', 'East'],
  ["ShadowtownLight", 'PvP', 'West'],
  ["ShienLight", 'RP-PvE', '', 'East'],
  ["Shii-ChoLight", 'PvE', 'East'],
  ["Sith Meditation SphereLight", 'PvE', 'East'],
  ["Sith WyrmLight", 'PvE', 'East'],
  ["SoresuLight", 'PvE', 'West'],
  ["Space SlugLight", 'PvE', 'West'],
  ["Sword of Ajunta PallLight", 'PvP', 'East'],
  ["Tarro BloodLight", 'PvE', 'East'],
  ["Telos Restoration ProjectLight", 'PvE', 'East'],
  ["TerentatekLight", 'PvP', 'East'],
  ["Thana VeshLight", 'PvE', 'East'],
  ["The BastionStandard", 'PvP', 'West'],
  ["The ConstantLight", 'PvE', 'East'],
  ["The CorsairLight", 'PvE', 'East'],
  ["The CourageousLight", 'PvE', 'East'],
  ["The Crucible PitsLight", 'PvP', 'West'],
  ["The Deadweight Light", 'PvP', 'East'],
  ["The DefenestratorLight", 'PvE', 'East'],
  ["The Ebon HawkStandard", 'RP-PvE', '', 'East'],
  ["The FatmanStandard", 'PvP', 'East'],
  ["The HarbingerStandard", 'PvE', 'West'],
  ["The Jekk'Jekk TarrLight", 'PvE', 'West'],
  ["The MawLight", 'PvP', 'West'],
  ["The RazorLight", 'PvE', 'East'],
  ["The ShadowlandsStandard", 'PvE', 'East'],
  ["The SwiftsureLight", 'PvP', 'West'],
  ["The Twin SpearsLight", 'PvP', 'East'],
  ["Thendys Noori Light", 'PvP', 'East'],
  ["Veeboo LunxLight", 'PvE', 'West'],
  ["VeelaLight", 'PvP', 'East'],
  ["Ven ZallowLight", 'RP-PvP', '', 'East'],
  ["VornskrLight", 'PvE', 'West'],
  ["Vrook LamarLight", 'RP-PvE', '', 'West'],
  ["Vulkar HighwayLight", 'PvP', 'East'],
  ["Wall of LightLight", 'PvE', 'West'],
  ["Warriors of the ShadowLight", 'PvP', 'West'],
  ["Whitebeam RunLight", 'PvE', 'East'],
  ["Wound in the ForceLight", 'PvP', 'West'],
  ["ZaalbarLight", 'PvE', 'West'],
  ["Zakkeg BeastLight", 'PvE', 'West'],
  ["Zez-Kai EllLight", 'PvE', 'East'],
  ["Ahto CityLight", 'PvP', 'English'],
  ["AtrisLight", 'PvP', 'French'],
  ["Bacca's BladeLight", 'PvE', 'English'],
  ["Bao-DurLight", 'PvE', 'English'],
  ["Baron DeathmarkLight", 'PvP', 'French'],
  ["Basilisk DroidLight", 'PvP', 'English'],
  ["Battle MeditationHeavy", 'RP-PvE', '', 'French'],
  ["BloodworthyLight", 'PvP', 'English'],
  ["Blotus the HuttLight", 'PvP', 'German'],
  ["BriannaLight", 'PvP', 'German'],
  ["Cassus FettLight", 'RP-PvE', '', 'German'],
  ["ChuundarLight", 'PvP', 'English'],
  ["Darth AndedduLight", 'PvE', 'German'],
  ["Darth NihilusStandard", 'PvP', 'French'],
  ["Darth Revan's MaskLight", 'PvP', 'German'],
  ["Darth TrayaLight", 'PvP', 'German'],
  ["Dol GrennLight", 'PvP', 'French'],
  ["Dreypa's OublietteLight", 'PvE', 'German'],
  ["Dune BanthaLight", 'PvE', 'English'],
  ["Dxun Battle CircleLight", 'PvE', 'English'],
  ["Exar KunLight", 'PvE', 'German'],
  ["Exis StationLight", 'PvP', 'German'],
  ["Eye of AshlanaeLight", 'PvE', 'English'],
  ["Flames of the CrucibleLight", 'PvE', 'English'],
  ["Force HarvesterLight", 'PvE', 'German'],
  ["FrostclawLight", 'PvE', 'English'],
  ["Gnawer's RoostLight", 'PvP', 'German'],
  ["Goluud CorridorLight", 'PvE', 'English'],
  ["Handmaidens of AtrisLight", 'PvE', 'German'],
  ["Hex DroidLight", 'PvP', 'English'],
  ["Hidden BeksLight", 'PvE', 'English'],
  ["Hrakert RiftLight", 'PvP', 'French'],
  ["HssissLight", 'PvE', 'French'],
  ["HuntmasterLight", 'RP-PvP', '', 'French'],
  ["Hydian WayLight", 'PvE', 'English'],
  ["Jar'Kai SwordHeavy", 'PvP', 'German'],
  ["Jen'jidaiLight", 'RP-PvP', '', 'German'],
  ["Kai-kanLight", 'PvP', 'English'],
  ["Kellian JarroLight", 'PvE', 'English'],
  ["Kessel RunLight", 'RP-PvE', '', 'French'],
  ["Kissai CasteLight", 'PvE', 'French'],
  ["Legions of LettowLight", 'PvP', 'English'],
  ["Lenico GargantuanLight", 'PvE', 'German'],
  ["LoramarrLight", 'PvP', 'German'],
  ["Lord CalyphoLight", 'RP-PvP', '', 'English'],
  ["Ludo KresshLight", 'PvE', 'English'],
  ["Luka SeneLight", 'PvE', 'English'],
  ["Mantle of the ForceHeavy", 'PvE', 'French'],
  ["Mecrosa OrderLight", 'PvP', 'French'],
  ["Murakami OrchidLight", 'PvE', 'German'],
  ["Nightmare LandsHeavy", 'PvE', 'English'],
  ["NimanLight", 'PvP', 'English'],
  ["Odacer-Faustin AcademyLight", 'PvE', 'German'],
  ["Opila CrystalLight", 'PvE', 'German'],
  ["Peragus Mining FacilityLight", 'PvE', 'English'],
  ["Phateem Halls of KnowledgeLight", 'PvE', 'French'],
  ["Pius DeaLight", 'PvP', 'German'],
  ["Princess GaliaLight", 'PvP', 'French'],
  ["Rogue MoonLight", 'PvE', 'English'],
  ["Scepter of RagnosLight", 'PvP', 'English'],
  ["Senator ContispexLight", 'PvP', 'English'],
  ["Shaltin TunnelsLight", 'RP-PvE', '', 'English'],
  ["Sith TriumvirateLight", 'PvE', 'German'],
  ["Sith'ariLight", 'PvE', 'English'],
  ["Sluis ShipyardsLight", 'PvE', 'English'],
  ["Star MapLight", 'PvP', 'French'],
  ["Starstorm OneLight", 'PvP', 'English'],
  ["Stereb CitiesLight", 'PvE', 'German'],
  ["Supreme Commander StantorrsLight", 'PvE', 'German'],
  ["T3-M4Very Heavy", 'PvE', 'German'],
  ["Tassaa BareeshLight", 'PvP', 'English'],
  ["The Arkanian LegacyLight", 'PvE', 'English'],
  ["The CinziaLight", 'PvE', 'German'],
  ["The Exile's CrystalLight", 'PvP', 'English'],
  ["The Jedi TowerHeavy", 'PvE', 'German'],
  ["The Krath EnchanterLight", 'PvP', 'German'],
  ["The KumumgahLight", 'PvP', 'English'],
  ["The ProgenitorVery Heavy", 'RP-PvE', '', 'English'],
  ["The RavagerLight", 'PvP', 'English'],
  ["The Red EclipseHeavy", 'PvE', 'English'],
  ["The Restoration ZoneLight", 'PvP', 'German'],
  ["The Shadow RunnerLight", 'PvP', 'English'],
  ["Tomb of Freedon NaddHeavy", 'PvP', 'English'],
  ["Tott DoneetaLight", 'PvP', 'English'],
  ["Trask UlgoLight", 'RP-PvE', '', 'English'],
  ["Trayus AcademyLight", 'PvP', 'English'],
  ["Ula ViiLight", 'PvP', 'English'],
  ["Uthar WynnLight", 'PvP', 'English'],
  ["Vanjervalis ChainVery Heavy", 'RP-PvE', '', 'German'],
  ["Vodo-Siosk BaasLight", 'PvE', 'French'],
  ["Zayne CarrickLight", 'RP-PvE', '', 'German'],
  ["DalborraLight", 'PvE', 'English'],
  ["Gav DaragonLight", 'RP-PvE', '', 'English'],
  ["Master Dar'NalaLight", 'PvP', 'English']
]

puts "Creating SWTOR Games..."
VALID_SWTOR_SERVERS.each do |server_name, server_type|
  Swtor.create!(faction: "Republic", server_name: server_name, server_type: server_type)
  Swtor.create!(faction: "Empire", server_name: server_name, server_type: server_type)
end