--- 
- :domain: true
  :company: false
  :administration: false
  :word: www
- :domain: true
  :company: false
  :administration: true
  :word: account
- :domain: true
  :company: false
  :administration: false
  :word: blog
- :domain: true
  :company: false
  :administration: false
  :word: secure
- :domain: true
  :company: false
  :administration: false
  :word: login  
- :domain: true
  :company: false
  :administration: false
  :word: logout  
- :domain: true
  :company: false
  :administration: true
  :word: admin  
- :domain: true
  :company: false
  :administration: false
  :word: manage  
- :domain: true
  :company: false
  :administration: true
  :word: management
- :domain: true
  :company: false
  :administration: false
  :word: my
- :domain: true
  :company: false
  :administration: false
  :word: myaccount
- :domain: true
  :company: false
  :administration: false
  :word: mobile
- :domain: true
  :company: false
  :administration: true
  :word: moderator
- :domain: true
  :company: false
  :administration: false
  :word: m    
- :domain: true
  :company: true
  :administration: true
  :word: crumblin
- :domain: true
  :company: true
  :administration: false
  :word: digitalaugment
- :domain: true
  :company: true
  :administration: false
  :word: digitalaugmentinc  
- :domain: true
  :company: true
  :administration: false
  :word: da
  