class AddMissingDatabaseIndexes < ActiveRecord::Migration
  def up
    add_index(:announcements, :community_game_id) unless index_exists?(:announcements, :community_game_id)
    add_index(:announcements, :character_id) unless index_exists?(:announcements, :character_id)
    add_index(:characters, :played_game_id) unless index_exists?(:characters, :played_game_id)
    add_index(:characters_community_applications, :character_id) unless index_exists?(:characters_community_applications, :character_id)
    add_index(:characters_community_applications, :community_application_id, name: "cca_ca_id") unless index_exists?(:characters_community_applications, :community_application_id)
    add_index(:comments, :character_id) unless index_exists?(:comments, :character_id)
    add_index(:communities, :community_plan_id) unless index_exists?(:communities, :community_plan_id)
    add_index(:communities, :charge_exempt_authorizer_id) unless index_exists?(:communities, :charge_exempt_authorizer_id)
    add_index(:discussion_spaces, :community_game_id) unless index_exists?(:discussion_spaces, :community_game_id)
    add_index(:discussions, :character_id) unless index_exists?(:discussions, :character_id)
    add_index(:events, :community_game_id) unless index_exists?(:events, :community_game_id)
    add_index(:invites, :character_id) unless index_exists?(:invites, :character_id)
    add_index(:invoice_items, [:item_id, :item_type]) unless index_exists?(:invoice_items, [:item_id, :item_type])
    add_index(:invoice_items, :community_id) unless index_exists?(:invoice_items, :community_id)
    add_index(:invoice_items, :invoice_id) unless index_exists?(:invoice_items, :invoice_id)
    add_index(:invoices, :user_id) unless index_exists?(:invoices, :user_id)
    add_index(:page_spaces, :community_game_id) unless index_exists?(:page_spaces, :community_game_id)
    add_index(:played_games, :game_id) unless index_exists?(:played_games, :game_id)
    add_index(:played_games, :user_profile_id) unless index_exists?(:played_games, :user_profile_id)
    add_index(:roster_assignments, :community_game_id) unless index_exists?(:roster_assignments, :community_game_id)
    add_index(:roster_assignments, :character_id) unless index_exists?(:roster_assignments, :character_id)
  end

  def down
    remove_index(:announcements, :community_game_id)
    remove_index(:announcements, :character_id)
    remove_index(:characters, :played_game_id)
    remove_index(:characters_community_applications, :character_id)
    remove_index(:characters_community_applications, :community_application_id)
    remove_index(:comments, :character_id)
    remove_index(:communities, :community_plan_id)
    remove_index(:communities, :charge_exempt_authorizer_id)
    remove_index(:discussion_spaces, :community_game_id)
    remove_index(:discussions, :character_id)
    remove_index(:events, :community_game_id)
    remove_index(:invites, :character_id)
    remove_index(:invoice_items, [:item_id, :item_type])
    remove_index(:invoice_items, :community_id)
    remove_index(:invoice_items, :invoice_id)
    remove_index(:invoices, :user_id)
    remove_index(:page_spaces, :community_game_id)
    remove_index(:played_games, :game_id)
    remove_index(:played_games, :user_profile_id)
    remove_index(:roster_assignments, :community_game_id)
    remove_index(:roster_assignments, :character_id)
  end
end
