require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommunityGamesController do

  # This should return the minimal set of attributes required to create a valid
  # CommunityGame. As you add validations to CommunityGame, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommunityGamesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all community_games as @community_games" do
      community_game = CommunityGame.create! valid_attributes
      get :index, {}, valid_session
      assigns(:community_games).should eq([community_game])
    end
  end

  describe "GET show" do
    it "assigns the requested community_game as @community_game" do
      community_game = CommunityGame.create! valid_attributes
      get :show, {:id => community_game.to_param}, valid_session
      assigns(:community_game).should eq(community_game)
    end
  end

  describe "GET new" do
    it "assigns a new community_game as @community_game" do
      get :new, {}, valid_session
      assigns(:community_game).should be_a_new(CommunityGame)
    end
  end

  describe "GET edit" do
    it "assigns the requested community_game as @community_game" do
      community_game = CommunityGame.create! valid_attributes
      get :edit, {:id => community_game.to_param}, valid_session
      assigns(:community_game).should eq(community_game)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CommunityGame" do
        expect {
          post :create, {:community_game => valid_attributes}, valid_session
        }.to change(CommunityGame, :count).by(1)
      end

      it "assigns a newly created community_game as @community_game" do
        post :create, {:community_game => valid_attributes}, valid_session
        assigns(:community_game).should be_a(CommunityGame)
        assigns(:community_game).should be_persisted
      end

      it "redirects to the created community_game" do
        post :create, {:community_game => valid_attributes}, valid_session
        response.should redirect_to(CommunityGame.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved community_game as @community_game" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommunityGame.any_instance.stub(:save).and_return(false)
        post :create, {:community_game => {}}, valid_session
        assigns(:community_game).should be_a_new(CommunityGame)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommunityGame.any_instance.stub(:save).and_return(false)
        post :create, {:community_game => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested community_game" do
        community_game = CommunityGame.create! valid_attributes
        # Assuming there are no other community_games in the database, this
        # specifies that the CommunityGame created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CommunityGame.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => community_game.to_param, :community_game => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested community_game as @community_game" do
        community_game = CommunityGame.create! valid_attributes
        put :update, {:id => community_game.to_param, :community_game => valid_attributes}, valid_session
        assigns(:community_game).should eq(community_game)
      end

      it "redirects to the community_game" do
        community_game = CommunityGame.create! valid_attributes
        put :update, {:id => community_game.to_param, :community_game => valid_attributes}, valid_session
        response.should redirect_to(community_game)
      end
    end

    describe "with invalid params" do
      it "assigns the community_game as @community_game" do
        community_game = CommunityGame.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommunityGame.any_instance.stub(:save).and_return(false)
        put :update, {:id => community_game.to_param, :community_game => {}}, valid_session
        assigns(:community_game).should eq(community_game)
      end

      it "re-renders the 'edit' template" do
        community_game = CommunityGame.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommunityGame.any_instance.stub(:save).and_return(false)
        put :update, {:id => community_game.to_param, :community_game => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested community_game" do
      community_game = CommunityGame.create! valid_attributes
      expect {
        delete :destroy, {:id => community_game.to_param}, valid_session
      }.to change(CommunityGame, :count).by(-1)
    end

    it "redirects to the community_games list" do
      community_game = CommunityGame.create! valid_attributes
      delete :destroy, {:id => community_game.to_param}, valid_session
      response.should redirect_to(community_games_url)
    end
  end

end
