require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommunityApplicationsController do

  # This should return the minimal set of attributes required to create a valid
  # CommunityApplication. As you add validations to CommunityApplication, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all community_applications as @community_applications" do
      community_application = CommunityApplication.create! valid_attributes
      get :index
      assigns(:community_applications).should eq([community_application])
    end
  end

  describe "GET show" do
    it "assigns the requested community_application as @community_application" do
      community_application = CommunityApplication.create! valid_attributes
      get :show, :id => community_application.id.to_s
      assigns(:community_application).should eq(community_application)
    end
  end

  describe "GET new" do
    it "assigns a new community_application as @community_application" do
      get :new
      assigns(:community_application).should be_a_new(CommunityApplication)
    end
  end

  describe "GET edit" do
    it "assigns the requested community_application as @community_application" do
      community_application = CommunityApplication.create! valid_attributes
      get :edit, :id => community_application.id.to_s
      assigns(:community_application).should eq(community_application)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CommunityApplication" do
        expect {
          post :create, :community_application => valid_attributes
        }.to change(CommunityApplication, :count).by(1)
      end

      it "assigns a newly created community_application as @community_application" do
        post :create, :community_application => valid_attributes
        assigns(:community_application).should be_a(CommunityApplication)
        assigns(:community_application).should be_persisted
      end

      it "redirects to the created community_application" do
        post :create, :community_application => valid_attributes
        response.should redirect_to(CommunityApplication.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved community_application as @community_application" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommunityApplication.any_instance.stub(:save).and_return(false)
        post :create, :community_application => {}
        assigns(:community_application).should be_a_new(CommunityApplication)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommunityApplication.any_instance.stub(:save).and_return(false)
        post :create, :community_application => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested community_application" do
        community_application = CommunityApplication.create! valid_attributes
        # Assuming there are no other community_applications in the database, this
        # specifies that the CommunityApplication created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CommunityApplication.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => community_application.id, :community_application => {'these' => 'params'}
      end

      it "assigns the requested community_application as @community_application" do
        community_application = CommunityApplication.create! valid_attributes
        put :update, :id => community_application.id, :community_application => valid_attributes
        assigns(:community_application).should eq(community_application)
      end

      it "redirects to the community_application" do
        community_application = CommunityApplication.create! valid_attributes
        put :update, :id => community_application.id, :community_application => valid_attributes
        response.should redirect_to(community_application)
      end
    end

    describe "with invalid params" do
      it "assigns the community_application as @community_application" do
        community_application = CommunityApplication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommunityApplication.any_instance.stub(:save).and_return(false)
        put :update, :id => community_application.id.to_s, :community_application => {}
        assigns(:community_application).should eq(community_application)
      end

      it "re-renders the 'edit' template" do
        community_application = CommunityApplication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommunityApplication.any_instance.stub(:save).and_return(false)
        put :update, :id => community_application.id.to_s, :community_application => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested community_application" do
      community_application = CommunityApplication.create! valid_attributes
      expect {
        delete :destroy, :id => community_application.id.to_s
      }.to change(CommunityApplication, :count).by(-1)
    end

    it "redirects to the community_applications list" do
      community_application = CommunityApplication.create! valid_attributes
      delete :destroy, :id => community_application.id.to_s
      response.should redirect_to(community_applications_url)
    end
  end

end
