require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RosterAssignmentsController do

  # This should return the minimal set of attributes required to create a valid
  # RosterAssignment. As you add validations to RosterAssignment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all roster_assignments as @roster_assignments" do
      roster_assignment = RosterAssignment.create! valid_attributes
      get :index
      assigns(:roster_assignments).should eq([roster_assignment])
    end
  end

  describe "GET show" do
    it "assigns the requested roster_assignment as @roster_assignment" do
      roster_assignment = RosterAssignment.create! valid_attributes
      get :show, :id => roster_assignment.id.to_s
      assigns(:roster_assignment).should eq(roster_assignment)
    end
  end

  describe "GET new" do
    it "assigns a new roster_assignment as @roster_assignment" do
      get :new
      assigns(:roster_assignment).should be_a_new(RosterAssignment)
    end
  end

  describe "GET edit" do
    it "assigns the requested roster_assignment as @roster_assignment" do
      roster_assignment = RosterAssignment.create! valid_attributes
      get :edit, :id => roster_assignment.id.to_s
      assigns(:roster_assignment).should eq(roster_assignment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RosterAssignment" do
        expect {
          post :create, :roster_assignment => valid_attributes
        }.to change(RosterAssignment, :count).by(1)
      end

      it "assigns a newly created roster_assignment as @roster_assignment" do
        post :create, :roster_assignment => valid_attributes
        assigns(:roster_assignment).should be_a(RosterAssignment)
        assigns(:roster_assignment).should be_persisted
      end

      it "redirects to the created roster_assignment" do
        post :create, :roster_assignment => valid_attributes
        response.should redirect_to(RosterAssignment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved roster_assignment as @roster_assignment" do
        # Trigger the behavior that occurs when invalid params are submitted
        RosterAssignment.any_instance.stub(:save).and_return(false)
        post :create, :roster_assignment => {}
        assigns(:roster_assignment).should be_a_new(RosterAssignment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RosterAssignment.any_instance.stub(:save).and_return(false)
        post :create, :roster_assignment => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested roster_assignment" do
        roster_assignment = RosterAssignment.create! valid_attributes
        # Assuming there are no other roster_assignments in the database, this
        # specifies that the RosterAssignment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RosterAssignment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => roster_assignment.id, :roster_assignment => {'these' => 'params'}
      end

      it "assigns the requested roster_assignment as @roster_assignment" do
        roster_assignment = RosterAssignment.create! valid_attributes
        put :update, :id => roster_assignment.id, :roster_assignment => valid_attributes
        assigns(:roster_assignment).should eq(roster_assignment)
      end

      it "redirects to the roster_assignment" do
        roster_assignment = RosterAssignment.create! valid_attributes
        put :update, :id => roster_assignment.id, :roster_assignment => valid_attributes
        response.should redirect_to(roster_assignment)
      end
    end

    describe "with invalid params" do
      it "assigns the roster_assignment as @roster_assignment" do
        roster_assignment = RosterAssignment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RosterAssignment.any_instance.stub(:save).and_return(false)
        put :update, :id => roster_assignment.id.to_s, :roster_assignment => {}
        assigns(:roster_assignment).should eq(roster_assignment)
      end

      it "re-renders the 'edit' template" do
        roster_assignment = RosterAssignment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RosterAssignment.any_instance.stub(:save).and_return(false)
        put :update, :id => roster_assignment.id.to_s, :roster_assignment => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested roster_assignment" do
      roster_assignment = RosterAssignment.create! valid_attributes
      expect {
        delete :destroy, :id => roster_assignment.id.to_s
      }.to change(RosterAssignment, :count).by(-1)
    end

    it "redirects to the roster_assignments list" do
      roster_assignment = RosterAssignment.create! valid_attributes
      delete :destroy, :id => roster_assignment.id.to_s
      response.should redirect_to(roster_assignments_url)
    end
  end

end
