require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SentMessagesController do

#   describe "GET index" do
#     it "assigns all message_copies as @message_copies" do
#       message_copy = MessageCopy.create! valid_attributes
#       get :index
#       assigns(:message_copies).should eq([message_copy])
#     end
#   end
# 
#   describe "GET show" do
#     it "assigns the requested message_copy as @message_copy" do
#       message_copy = MessageCopy.create! valid_attributes
#       get :show, :id => message_copy.id.to_s
#       assigns(:message_copy).should eq(message_copy)
#     end
#   end
# 
#   describe "GET new" do
#     it "assigns a new message_copy as @message_copy" do
#       get :new
#       assigns(:message_copy).should be_a_new(MessageCopy)
#     end
#   end
# 
#   describe "GET edit" do
#     it "assigns the requested message_copy as @message_copy" do
#       message_copy = MessageCopy.create! valid_attributes
#       get :edit, :id => message_copy.id.to_s
#       assigns(:message_copy).should eq(message_copy)
#     end
#   end
# 
#   describe "POST create" do
#     describe "with valid params" do
#       it "creates a new MessageCopy" do
#         expect {
#           post :create, :message_copy => valid_attributes
#         }.to change(MessageCopy, :count).by(1)
#       end
# 
#       it "assigns a newly created message_copy as @message_copy" do
#         post :create, :message_copy => valid_attributes
#         assigns(:message_copy).should be_a(MessageCopy)
#         assigns(:message_copy).should be_persisted
#       end
# 
#       it "redirects to the created message_copy" do
#         post :create, :message_copy => valid_attributes
#         response.should redirect_to(MessageCopy.last)
#       end
#     end
# 
#     describe "with invalid params" do
#       it "assigns a newly created but unsaved message_copy as @message_copy" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         MessageCopy.any_instance.stub(:save).and_return(false)
#         post :create, :message_copy => {}
#         assigns(:message_copy).should be_a_new(MessageCopy)
#       end
# 
#       it "re-renders the 'new' template" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         MessageCopy.any_instance.stub(:save).and_return(false)
#         post :create, :message_copy => {}
#         response.should render_template("new")
#       end
#     end
#   end
# 
#   describe "PUT update" do
#     describe "with valid params" do
#       it "updates the requested message_copy" do
#         message_copy = MessageCopy.create! valid_attributes
#         # Assuming there are no other message_copies in the database, this
#         # specifies that the MessageCopy created on the previous line
#         # receives the :update_attributes message with whatever params are
#         # submitted in the request.
#         MessageCopy.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
#         put :update, :id => message_copy.id, :message_copy => {'these' => 'params'}
#       end
# 
#       it "assigns the requested message_copy as @message_copy" do
#         message_copy = MessageCopy.create! valid_attributes
#         put :update, :id => message_copy.id, :message_copy => valid_attributes
#         assigns(:message_copy).should eq(message_copy)
#       end
# 
#       it "redirects to the message_copy" do
#         message_copy = MessageCopy.create! valid_attributes
#         put :update, :id => message_copy.id, :message_copy => valid_attributes
#         response.should redirect_to(message_copy)
#       end
#     end
# 
#     describe "with invalid params" do
#       it "assigns the message_copy as @message_copy" do
#         message_copy = MessageCopy.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         MessageCopy.any_instance.stub(:save).and_return(false)
#         put :update, :id => message_copy.id.to_s, :message_copy => {}
#         assigns(:message_copy).should eq(message_copy)
#       end
# 
#       it "re-renders the 'edit' template" do
#         message_copy = MessageCopy.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         MessageCopy.any_instance.stub(:save).and_return(false)
#         put :update, :id => message_copy.id.to_s, :message_copy => {}
#         response.should render_template("edit")
#       end
#     end
#   end
# 
#   describe "DELETE destroy" do
#     it "destroys the requested message_copy" do
#       message_copy = MessageCopy.create! valid_attributes
#       expect {
#         delete :destroy, :id => message_copy.id.to_s
#       }.to change(MessageCopy, :count).by(-1)
#     end
# 
#     it "redirects to the message_copies list" do
#       message_copy = MessageCopy.create! valid_attributes
#       delete :destroy, :id => message_copy.id.to_s
#       response.should redirect_to(message_copies_url)
#     end
#   end

end
