require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Subdomains::DiscussionSpacesController do

#   describe "GET index" do
#     it "assigns all discussion_spaces as @discussion_spaces" do
#       discussion_space = DiscussionSpace.create! valid_attributes
#       get :index
#       assigns(:discussion_spaces).should eq([discussion_space])
#     end
#   end
# 
#   describe "GET show" do
#     it "assigns the requested discussion_space as @discussion_space" do
#       discussion_space = DiscussionSpace.create! valid_attributes
#       get :show, :id => discussion_space.id.to_s
#       assigns(:discussion_space).should eq(discussion_space)
#     end
#   end
# 
#   describe "GET new" do
#     it "assigns a new discussion_space as @discussion_space" do
#       get :new
#       assigns(:discussion_space).should be_a_new(DiscussionSpace)
#     end
#   end
# 
#   describe "GET edit" do
#     it "assigns the requested discussion_space as @discussion_space" do
#       discussion_space = DiscussionSpace.create! valid_attributes
#       get :edit, :id => discussion_space.id.to_s
#       assigns(:discussion_space).should eq(discussion_space)
#     end
#   end
# 
#   describe "POST create" do
#     describe "with valid params" do
#       it "creates a new DiscussionSpace" do
#         expect {
#           post :create, :discussion_space => valid_attributes
#         }.to change(DiscussionSpace, :count).by(1)
#       end
# 
#       it "assigns a newly created discussion_space as @discussion_space" do
#         post :create, :discussion_space => valid_attributes
#         assigns(:discussion_space).should be_a(DiscussionSpace)
#         assigns(:discussion_space).should be_persisted
#       end
# 
#       it "redirects to the created discussion_space" do
#         post :create, :discussion_space => valid_attributes
#         response.should redirect_to(DiscussionSpace.last)
#       end
#     end
# 
#     describe "with invalid params" do
#       it "assigns a newly created but unsaved discussion_space as @discussion_space" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         DiscussionSpace.any_instance.stub(:save).and_return(false)
#         post :create, :discussion_space => {}
#         assigns(:discussion_space).should be_a_new(DiscussionSpace)
#       end
# 
#       it "re-renders the 'new' template" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         DiscussionSpace.any_instance.stub(:save).and_return(false)
#         post :create, :discussion_space => {}
#         response.should render_template("new")
#       end
#     end
#   end
# 
#   describe "PUT update" do
#     describe "with valid params" do
#       it "updates the requested discussion_space" do
#         discussion_space = DiscussionSpace.create! valid_attributes
#         # Assuming there are no other discussion_spaces in the database, this
#         # specifies that the DiscussionSpace created on the previous line
#         # receives the :update_attributes message with whatever params are
#         # submitted in the request.
#         DiscussionSpace.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
#         put :update, :id => discussion_space.id, :discussion_space => {'these' => 'params'}
#       end
# 
#       it "assigns the requested discussion_space as @discussion_space" do
#         discussion_space = DiscussionSpace.create! valid_attributes
#         put :update, :id => discussion_space.id, :discussion_space => valid_attributes
#         assigns(:discussion_space).should eq(discussion_space)
#       end
# 
#       it "redirects to the discussion_space" do
#         discussion_space = DiscussionSpace.create! valid_attributes
#         put :update, :id => discussion_space.id, :discussion_space => valid_attributes
#         response.should redirect_to(discussion_space)
#       end
#     end
# 
#     describe "with invalid params" do
#       it "assigns the discussion_space as @discussion_space" do
#         discussion_space = DiscussionSpace.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         DiscussionSpace.any_instance.stub(:save).and_return(false)
#         put :update, :id => discussion_space.id.to_s, :discussion_space => {}
#         assigns(:discussion_space).should eq(discussion_space)
#       end
# 
#       it "re-renders the 'edit' template" do
#         discussion_space = DiscussionSpace.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         DiscussionSpace.any_instance.stub(:save).and_return(false)
#         put :update, :id => discussion_space.id.to_s, :discussion_space => {}
#         response.should render_template("edit")
#       end
#     end
#   end
# 
#   describe "DELETE destroy" do
#     it "destroys the requested discussion_space" do
#       discussion_space = DiscussionSpace.create! valid_attributes
#       expect {
#         delete :destroy, :id => discussion_space.id.to_s
#       }.to change(DiscussionSpace, :count).by(-1)
#     end
# 
#     it "redirects to the discussion_spaces list" do
#       discussion_space = DiscussionSpace.create! valid_attributes
#       delete :destroy, :id => discussion_space.id.to_s
#       response.should redirect_to(discussion_spaces_url)
#     end
#   end

end
