require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Subdomains::DiscussionSpacesController do
  let(:user) { DefaultObjects.user }
  let(:admin) { DefaultObjects.community_admin }
  let(:non_member) { create(:user_profile).user }
  let(:community) { DefaultObjects.community }
  let(:space) { DefaultObjects.discussion_space }
  let(:discussion) { DefaultObjects.discussion }

  before(:each) do
    @request.host = "#{community.subdomain}.example.com"
  end

  describe "GET index" do
    it "assigns all discussion_spaces as @discussion_spaces when authenticated as a member" do
      space
      sign_in user
      get :index
      assigns(:discussion_spaces).should have(community.discussion_spaces.count).things
    end
    
    it "should redirect to new user session path when not authenticated as a user" do
      get :index
      response.should redirect_to(new_user_session_url(subdomain: 'secure', protocol: "https://"))
    end
    
    it "should respond forbidden when not a member" do
      sign_in non_member
      get :index
      response.should be_forbidden
    end
  end

  describe "GET show" do
    it "assigns the requested discussion_space as @discussion_space when authenticated as a member" do
      sign_in user
      get :show, :id => space
      assigns(:discussion_space).should eq(space)
    end
    
    it "should redirected to new user session path when not authenticated as a user" do
      get :show, :id => space
      response.should redirect_to(new_user_session_url(subdomain: 'secure', protocol: "https://"))
    end
    
    it "should respond forbidden when not a member" do
      sign_in non_member
      get :show, :id => space
      response.should be_forbidden
    end    
  end

  describe "GET new" do
    it "assigns a new discussion_space as @discussion_space when authenticated as community admin" do
      sign_in admin
      get :new
      assigns(:discussion_space).should be_a_new(DiscussionSpace)
    end
    
    it "should redirect to new user session path when not authenticated as a user" do
      get :new
      response.should redirect_to(new_user_session_url(subdomain: 'secure', protocol: "https://"))
    end 
    
    it "should respond forbidden when not a member" do
      sign_in non_member
      get :new
      response.should be_forbidden
    end
    
    it "should respond forbidden when a member without permissions" do
      sign_in user
      get :new
      response.should be_forbidden
    end
  end

  describe "GET edit" do
    it "assigns the requested discussion_space as @discussion_space when authenticated as community admin" do
      sign_in admin
      get :edit, :id => space.id.to_s
      assigns(:discussion_space).should eq(space)
    end
    
    it "should redirect to new user session path when not authenticated as a user" do
      get :edit, :id => space.id.to_s
      response.should redirect_to(new_user_session_url(subdomain: 'secure', protocol: "https://"))
    end
    
    it "should respond forbidden when not a member" do
      sign_in non_member
      get :edit, :id => space.id.to_s
      response.should be_forbidden
    end 
  end

  describe "POST create when authenticated as admin" do
    before(:each) {
      sign_in admin
    }
  
    describe "with valid params" do
      it "creates a new DiscussionSpace" do
        expect {
          post :create, :discussion_space => attributes_for(:discussion_space)
        }.to change(DiscussionSpace, :count).by(1)
      end

      it "assigns a newly created discussion_space as @discussion_space" do
        post :create, :discussion_space => attributes_for(:discussion_space)
        assigns(:discussion_space).should be_a(DiscussionSpace)
        assigns(:discussion_space).should be_persisted
      end

      it "redirects to the created discussion_space" do
        post :create, :discussion_space => attributes_for(:discussion_space)
        response.should redirect_to(DiscussionSpace.last)
      end
      
      it "should create an activity" do
        expect {
          post :create, :discussion_space => attributes_for(:discussion_space)
        }.to change(Activity, :count).by(1)
        
        activity = Activity.last
        activity.target_type.should eql "DiscussionSpace"
        activity.action.should eql 'created'
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved discussion_space as @discussion_space" do
        post :create, :discussion_space => attributes_for(:discussion_space, :name => nil)
        assigns(:discussion_space).should be_a_new(DiscussionSpace)
      end

      it "re-renders the 'new' template" do
        post :create, :discussion_space => attributes_for(:discussion_space, :name => nil)
        response.should render_template("new")
      end
      
      it "should not create an activity" do
        expect {
          post :create, :discussion_space => attributes_for(:discussion_space, :name => nil)
        }.to change(Activity, :count).by(0)
      end
    end
  end
  
  describe "POST create" do
    it "should redirected to new user session path when not authenticated as a user" do
      post :create, :discussion_space => attributes_for(:discussion_space)
      response.should redirect_to(new_user_session_url(subdomain: 'secure', protocol: "https://"))
    end
    
    it "should respond forbidden when not a member" do
      sign_in non_member
      post :create, :discussion_space => attributes_for(:discussion_space)
      response.should be_forbidden
    end    
  end

  describe "PUT update when authenticated as owner" do
    before(:each) {
      sign_in admin
    }
  
    describe "with valid params" do
      it "updates the requested discussion_space" do
        put :update, :id => space.id, :discussion_space => {:name => "New Name"}
        DiscussionSpace.find(space).name.should eql "New Name"
      end

      it "assigns the requested discussion_space as @discussion_space" do
        put :update, :id => space.id, :discussion_space => {:name => "New Name"}
        assigns(:discussion_space).should eq(space)
      end

      it "redirects to the discussion_space" do
        put :update, :id => space.id, :discussion_space => {:name => "New Name"}
        response.should redirect_to(space)
      end
      
      it "should create an Activity when attributes change" do
        put :update, :id => space.id, :discussion_space => {:name => "New Name"}
        activity = Activity.last
        activity.target_type.should eql "DiscussionSpace"
        activity.action.should eql 'edited'
      end
      
      it "should not create an Activity when attributes don't change" do        
        space
        expect {
          put :update, :id => space.id, :discussion_space => {:name => space.name}
        }.to change(Activity, :count).by(0)
      end
    end

    describe "with invalid params" do
      it "assigns the discussion_space as @discussion_space" do
        put :update, :id => space.id.to_s, :discussion_space => {:name => nil}
        assigns(:discussion_space).should eq(space)
      end

      it "re-renders the 'edit' template" do
        put :update, :id => space.id.to_s, :discussion_space => {:name => nil}
        response.should render_template("edit")
      end
    end
  end

  describe "PUT update" do
    it "should redirected to new user session path when not authenticated as a user" do
      put :update, :id => space.id, :discussion_space => {:name => "New Name"}
      response.should redirect_to(new_user_session_url(subdomain: 'secure', protocol: "https://"))
    end
    
    it "should respond forbidden when not a member" do
      sign_in non_member
      put :update, :id => space.id, :discussion_space => {:name => "New Name"}
      response.should be_forbidden
    end    
  end

  describe "DELETE destroy" do
    it "destroys the requested discussion_space when authenticated as a member" do
      space
      sign_in admin
      expect {
        delete :destroy, :id => space.id.to_s
      }.to change(DiscussionSpace, :count).by(-1)
    end

    it "redirects to the discussion_spaces list when authenticated as a member" do
      sign_in admin
      delete :destroy, :id => space.id.to_s
      response.should redirect_to(discussion_spaces_url)
    end
    
    it "should redirected to new user session path when not authenticated as a user" do
      delete :destroy, :id => space.id.to_s
      response.should redirect_to(new_user_session_url(subdomain: 'secure', protocol: "https://"))
    end
    
    it "should respond forbidden when not a member" do
      sign_in non_member
      delete :destroy, :id => space.id.to_s
      response.should be_forbidden
    end
  end
end
