require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Subdomains::SupportedGamesController do
  let(:member) { DefaultObjects.user }
  let(:admin) { DefaultObjects.community_admin }
  let(:non_member) { create(:user_profile).user }
  let(:community) { DefaultObjects.community }
  
  let(:supported_game) { create(:supported_game) }
  let(:valid_attributes) { attributes_for(:supported_game_att) }

  before(:each) do
    @request.host = "#{community.subdomain}.example.com"
  end

  describe "GET index" do
    it "assigns all supported_games as @supported_games when authenticated as a member" do
      sign_in member
      get :index
      assigns(:supported_games).should eq(community.supported_games)
    end
    
    it "should redirect to new user session path when not authenticated as a user" do
      get :index
      response.should redirect_to(new_user_session_path)
    end
    
    it "should respond forbidden when not a member" do
      sign_in non_member
      get :index
      response.should be_forbidden
    end
  end

  describe "GET show" do
    it "assigns the requested supported_game as @supported_game when authenticated as a member" do
      sign_in member
      supported_game
      get :show, :id => supported_game.id
      assigns(:supported_game).should eq(supported_game)
    end
    
    it "should redirected to new user session path when not authenticated as a user" do
      get :show, :id => supported_game
      response.should redirect_to(new_user_session_path)
    end
    
    it "should respond forbidden when not a member" do
      sign_in non_member
      get :show, :id => supported_game
      response.should be_forbidden
    end 
  end

  describe "GET new" do
    it "assigns a new supported_game as @supported_game when authenticated as community admin" do
      sign_in admin
      get :new
      assigns(:supported_game).should be_a_new(SupportedGame)
    end
    
    it "should redirect to new user session path when not authenticated as a user" do
      get :new
      response.should redirect_to(new_user_session_path)
    end 
    
    it "should respond forbidden when not a member" do
      sign_in non_member
      get :new
      response.should be_forbidden
    end
    
    it "should respond forbidden when a member without permissions" do
      sign_in member
      get :new
      response.should be_forbidden
    end
  end

  describe "GET edit" do
    it "assigns the requested supported_game as @supported_game when authenticated as community admin" do
      sign_in admin
      supported_game
      get :edit, :id => supported_game.id
      assigns(:supported_game).should eq(supported_game)
    end
    
    it "should redirect to new user session path when not authenticated as a user" do
      get :edit, :id => supported_game.id.to_s
      response.should redirect_to(new_user_session_path)
    end
    
    it "should respond forbidden when not a member" do
      sign_in non_member
      get :edit, :id => supported_game.id.to_s
      response.should be_forbidden
    end 
    
    it "should respond forbidden when a member without permissions" do
      sign_in member
      get :edit, :id => supported_game.id.to_s
      response.should be_forbidden
    end
  end

  describe "POST create when authenticated as community admin" do
    before(:each) {
      sign_in admin
    }
    
    describe "with valid params" do
      it "creates a new SupportedGame" do
        expect {
          post :create, :supported_game => valid_attributes
        }.to change(SupportedGame, :count).by(1)
      end

      it "assigns a newly created supported_game as @supported_game" do
        post :create, :supported_game => valid_attributes
        assigns(:supported_game).should be_a(SupportedGame)
        assigns(:supported_game).should be_persisted
      end

      it "redirects to the created supported_game" do
        post :create, :supported_game => valid_attributes
        response.should redirect_to(SupportedGame.last)
      end
      
      it "should create an activity" do
        expect {
          post :create, :supported_game => valid_attributes
        }.to change(Activity, :count).by(1)
        
        activity = Activity.last
        activity.target_type.should eql "SupportedGame"
        activity.action.should eql 'created'
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved supported_game as @supported_game" do
        post :create, :supported_game => {:game_type => DefaultObjects.wow.class.name}
        assigns(:supported_game).should be_a_new(SupportedGame)
      end

      it "re-renders the 'new' template" do
        post :create, :supported_game => {:game_type => DefaultObjects.wow.class.name}
        response.should render_template("new")
      end
      
      it "should not create an activity" do
        expect {
          post :create, :supported_game => {:game_type => DefaultObjects.wow.class.name}
        }.to change(Activity, :count).by(0)
      end
    end
  end
  
  describe "POST create" do
    it "should redirected to new user session path when not authenticated as a user" do
      post :create, :supported_game => valid_attributes
      response.should redirect_to(new_user_session_path)
    end
    
    it "should respond forbidden when not a member" do
      sign_in non_member
      post :create, :supported_game => valid_attributes
      response.should be_forbidden
    end
    
    it "should respond forbidden when a member without permissions" do
      sign_in member
      post :create, :supported_game => valid_attributes
      response.should be_forbidden
    end   
  end

  describe "PUT update when authenticated as community admin" do
    before(:each) {
      sign_in admin
    }
    
    describe "with valid params" do
      it "updates the requested supported_game" do
        put :update, :id => supported_game.id, :supported_game => {:name => "New Name", :faction => supported_game.faction, :server_name => supported_game.server_name}
        SupportedGame.find(supported_game).name.should eql "New Name"
      end

      it "assigns the requested supported_game as @supported_game" do
        put :update, :id => supported_game.id, :supported_game => valid_attributes
        assigns(:supported_game).should eq(supported_game)
      end

      it "redirects to the supported_game" do
        put :update, :id => supported_game.id, :supported_game => valid_attributes
        response.should redirect_to(supported_game)
      end
      
      it "should create an Activity when attributes change" do
        put :update, :id => supported_game.id, :supported_game => valid_attributes
        activity = Activity.last
        activity.target_type.should eql "SupportedGame"
        activity.action.should eql 'edited'
      end
      
      it "should not create an Activity when attributes don't change" do        
        supported_game
        expect {
          put :update, :id => supported_game.id, :supported_game => {:name => supported_game.name, :faction => supported_game.faction, :server_name => supported_game.server_name}
        }.to change(Activity, :count).by(0)
      end
    end

    describe "with invalid params" do
      it "assigns the supported_game as @supported_game" do
        put :update, :id => supported_game.id, :supported_game => {:name => nil}
        assigns(:supported_game).should eq(supported_game)
      end

      it "re-renders the 'edit' template" do
        put :update, :id => supported_game.id, :supported_game => {:name => nil}
        response.should render_template("edit")
      end
    end
  end

  describe "PUT update" do
    it "should redirected to new user session path when not authenticated as a user" do
      put :update, :id => supported_game.id, :supported_game => valid_attributes
      response.should redirect_to(new_user_session_path)
    end
    
    it "should respond forbidden when not a member" do
      sign_in non_member
      put :update, :id => supported_game.id, :supported_game => valid_attributes
      response.should be_forbidden
    end
    
    it "should respond forbidden when a member without permissions" do
      sign_in member
      put :update, :id => supported_game.id, :supported_game => valid_attributes
      response.should be_forbidden
    end   
  end

  describe "DELETE destroy" do
    it "destroys the requested supported_game when authenticated as community admin" do
      sign_in admin
      supported_game
      expect {
        delete :destroy, :id => supported_game.id
      }.to change(SupportedGame, :count).by(-1)
    end

    it "redirects to the subdomains_supported_games list when authenticated as community admin" do
      sign_in admin
      delete :destroy, :id => supported_game.id
      response.should redirect_to(supported_games_url)
    end
    
    it "should redirected to new user session path when not authenticated as a user" do
      delete :destroy, :id => supported_game.id.to_s
      response.should redirect_to(new_user_session_path)
    end
    
    it "should respond forbidden when not a member" do
      sign_in non_member
      delete :destroy, :id => supported_game.id.to_s
      response.should be_forbidden
    end
    
    it "should respond forbidden when a member without permissions" do
      sign_in member
      delete :destroy, :id => supported_game.id.to_s
      response.should be_forbidden
    end
  end

end
